
#!/usr/bin/env bash
set -euo pipefail

APP_DIR=${1:-marketplace}
RUBY_VERSION=$(ruby -v || true)
if [ -z "$RUBY_VERSION" ]; then
  echo "Ruby is required in Codespaces base images. Please choose a Ruby image or install Ruby." >&2
  exit 1
fi

# Ensure bundler & rails
if ! command -v bundler >/dev/null 2>&1; then
  gem install bundler
fi
if ! command -v rails >/dev/null 2>&1; then
  gem install rails
fi

# Create Rails app if not exists
if [ ! -d "$APP_DIR" ]; then
  rails new "$APP_DIR" --database=sqlite3 --javascript=importmap --skip-test
fi

cd "$APP_DIR"

# Add required gems
bundle add sidekiq redis rspec-rails simplecov

# Install & init RSpec
bundle install
if [ ! -f spec/spec_helper.rb ]; then
  bin/rails generate rspec:install
fi

# Ensure directories
mkdir -p app/channels app/jobs app/models/concerns app/javascript/channels app/javascript/controllers          config/initializers          spec/channels spec/models spec/jobs spec/factories          .github/workflows

# Copy files from parent (if uploaded at repo root)
copy_if_exists(){
  src="$1"; dst="$2";
  if [ -f "../$src" ]; then
    cp "../$src" "$dst"
  fi
}
copy_dir_if_exists(){
  src="$1"; dst="$2";
  if [ -d "../$src" ]; then
    cp -R "../$src/." "$dst"
  fi
}

# CI
copy_if_exists .github/workflows/ci.yml .github/workflows/ci.yml

# Configs
copy_if_exists config/cable.yml config/cable.yml
copy_if_exists config/sidekiq.yml config/sidekiq.yml
copy_if_exists config/initializers/broadcasts_auction_updates.rb config/initializers/broadcasts_auction_updates.rb

# App code
copy_if_exists app/channels/auction_channel.rb app/channels/auction_channel.rb
copy_if_exists app/jobs/auction_close_job.rb app/jobs/auction_close_job.rb
copy_if_exists app/jobs/auction_reminder_job.rb app/jobs/auction_reminder_job.rb
copy_if_exists app/models/concerns/auction_scheduler.rb app/models/concerns/auction_scheduler.rb
copy_if_exists app/models/concerns/broadcasts_auction_updates.rb app/models/concerns/broadcasts_auction_updates.rb
copy_if_exists app/javascript/channels/auction_channel.js app/javascript/channels/auction_channel.js
copy_if_exists app/javascript/controllers/auction_controller.js app/javascript/controllers/auction_controller.js

# Specs
copy_if_exists spec/spec_helper.rb spec/spec_helper.rb
copy_if_exists spec/channels/auction_channel_spec.rb spec/channels/auction_channel_spec.rb
copy_if_exists spec/models/bid_spec.rb spec/models/bid_spec.rb
copy_if_exists spec/jobs/auction_close_job_spec.rb spec/jobs/auction_close_job_spec.rb
copy_dir_if_exists spec/factories spec/factories

# Procfile (optional)
copy_if_exists Procfile Procfile

# --- BDD: add cucumber if not present ---
if ! grep -q 'cucumber-rails' Gemfile; then
  cat >> Gemfile <<'GEMS'

group :test do
  gem 'cucumber-rails', require: false
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'database_cleaner-active_record'
end
GEMS
  bundle install
  yes | bundle exec rails generate cucumber:install --capybara
fi

# Add a sample BDD feature & steps
mkdir -p features/step_definitions features/support
cat > features/bidding.feature <<'FEAT'
Feature: Bidding updates in real time
  As a buyer
  I want to see the highest bid update live
  So that I can react to overbids before the auction closes

  Scenario: Highest bid shows after placing a bid
    Given an active auction ending soon
    When I place a bid of 10.00 USD
    Then I should see the highest bid is 10.00 USD
FEAT

cat > features/step_definitions/bidding_steps.rb <<'STEPS'
Given('an active auction ending soon') do
  # Minimal placeholder; adapt to your app's actual models/routes
  # You can create Auction and visit the show page here if routes exist.
  # For now this is a pending step to be implemented by the team.
  pending
end

When('I place a bid of {float} USD') do |amount|
  pending
end

Then('I should see the highest bid is {float} USD') do |amount|
  pending
end
STEPS

# Ensure cucumber is runnable but won’t fail CI if steps pending
if [ ! -f features/support/env.rb ]; then
  echo "# Cucumber env settings are generated by cucumber-rails" > features/support/env.rb
fi

# Final tips to console
cat <<'DONE'

✅ Rails app ready in ./marketplace (or your chosen folder)
Next steps:
  1) Add `include AuctionScheduler` & enum to app/models/auction.rb once you generate that model.
  2) RSpec:  bundle exec rspec --format documentation
  3) Cucumber: bundle exec cucumber   (feature has pending steps you will implement)
  4) Commit & push branch, open PR (CI runs RSpec + Cucumber + coverage)
DONE
